apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "2dc6e0ba-352b-4ae4-9048-d5aa7b6b7676"
    keyvaultName: "key-pragma-m" # REPLACE with your Key Vault name
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: rsa-ecdh
          objectType: secret
          alias: rsa-ecdh
          objectFormat: pem
        - |
          objectName: ecc-ecdh
          objectType: secret
          alias: ecc-ecdh
          objectFormat: pem
    tenantId: "f31d6ebe-9b8a-4b9d-bcfc-3180ce1ff96c" # REPLACE with your Tenant ID
